package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            param("env.IMAGE_REGISTRY", "3.38.251.60:30002/msa-demo")
        }
        update {
            param("env.IMAGE_REGISTRY", "13.124.192.6:30002/msa-demo")
        }
        expect {
            password("env.REGISTRY_PASSWORD", "tangun123!", label = "Container Registry Password", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.REGISTRY_PASSWORD", "credentialsJSON:96e4d9e6-4f24-4241-8fd0-60cc2fdd88e2", label = "Container Registry Password", display = ParameterDisplay.HIDDEN)
        }
    }
}
