package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.kubernetesConnection
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.kubernetesExecutor
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            kubernetesConnection {
                id = "PROJECT_EXT_2"
                name = "Kubernetes Connection"
                apiServerUrl = "https://kubernetes.default.svc"
                namespace = "teamcity"
                authStrategy = clientCertificateAndKey {
                    clientKey = "credentialsJSON:9dd451ce-45dd-4626-b0d2-13eb48acf417"
                    clientCertificate = "credentialsJSON:564c3eaa-c5f7-4347-a8d8-f48e676f7ae8"
                }
                param("secure:authToken", "credentialsJSON:d964e465-11f6-47a7-a823-0f8945c98e0a")
            }
        }
        add {
            kubernetesExecutor {
                id = "PROJECT_EXT_3"
                connectionId = "PROJECT_EXT_2"
                profileName = "k8s-agents"
                buildsLimit = "2"
                serverURL = "http://teamcity-server.teamcity.svc:8111"
            }
        }
    }
}
