apiVersion: v1
kind: Secret
metadata:
  name: msa-postgres-secret
  namespace: msa-demo-gitops
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: msa-order-system
type: Opaque
stringData:
  POSTGRES_USER: "msa_user"
  POSTGRES_PASSWORD: "msa_secure_password_123"
  POSTGRES_DB: "orders_db"
  DATABASE_URL: "postgresql://msa_user:msa_secure_password_123@postgres-service:5432/orders_db"
